### PR TITLE
Schematron / Add rules for all packages.

### PR DESCRIPTION
**Pull request by fxprunayre**
Add a resources/schematron folder containing:
* rule folder with one file per package
* resources folder containing sample records to test all rules

All rules were extracted from ISO19115-1:2014 document from the UML diagrams Constraint section. Reference to the doc are added to each rule files eg.
```
See ISO19115-1:2014(E) page 24, Figure 19 Extent information classes
```

Rule contains multilingual message in English and French.

### CODE REVIEW

**Comment by tedhabermann** [comment]
Francois,

Thanks so much for this careful work... Our original plan was to have the rules and examples in each namespace directory. Does it make more sense to have them all in one separate directory...? 

Ted

**Comment by fxprunayre** [comment]
>  Does it make more sense to have them all in one separate directory...?

I don't know. I think it depends mainly how you want to "promote" this set of schematron rules. We could see it as an additional resources to the schema (like the XSLT transformations are) or give it more "legitimity"  and  have them close to the related XSDs.

It's also not that easy to write schematron tests that everybody agree on even if the rule on the standard is in most cases quite clear, the way you implement it could be done in different ways (eg. taking care of multilingual metadata, what does not empty means when you have gco:nilReason=withheld ?, ... ).

Anyway, I made one file per package and it's fine for me to have it as resources or next to the XSDs. If they move to the XSD folder, then we should keep the testing file as resources only to not have too much noise in the main folder I think.

BTW a review of the english diagnostics would be welcomed and FYI I'll review it more closely next week with some "real" users.

**Comment by PeterParslow** [comment]
François et al,
My understanding of 19115-3 is that the schematron rules are part of the standard (implementing some of the conformance requirements) – see A.1.2. The XSLTs are described as “artefacts to support … migration”.

I’m not sure this impacts the decision about which folder they sit in. It would lean towards keeping each set of Schematron rules with the XSDs. But ‘ease of use’ might lean us the other way … could we provide a ‘single point of entry’, presumably made of ‘includes’?

An interesting point about ‘schematron tests that everybody agree(s) on’. I see a parallel there with the text of the standard – our job as a project/editing team is to agree. What we agree then becomes part of the standard.

Peter

**Comment by jetgeo** [comment]
I believe that both the schematron rules and the example files should be in the namespace directories. They are closely related to the XSDs, and keeping them together makes it easier for users to see them in combination.

**Comment by tedhabermann** [comment]
Francois,
Seems like the consensus is having these rules/examples in the namespace directories. Would you have time to do that?
Ted

**Comment by fxprunayre** [comment]
Sure, will do that

**Comment by fxprunayre** [comment]
Files moved to packages.

**Pull request merged**
