### PR TITLE
Codelist updates

### PR DESCRIPTION
**Pull request by tedhabermann**
I updated the codelists in response to comments from NOAA.

### CODE REVIEW

**Comment by tedhabermann** [comment]
See Codelist page in wiki

**Comment by ebleys** [comment]
Sorry if this is old ground.
What is the rationale for gml:id as numeric rather than informative?
eg gml:id="_11861_17788" rather than gml:id="DQ_EvaluationMethodTypeCode_directInternal"
Cheers
e

**Comment by tedhabermann** [comment]
Evert,

These id’s were created by shapechange. I expect that they were done as numbers because the scope of these id’s is local to the file that contains them. GML generally contains a plethora of id’s and they are generally created without semantics. These ids are consistent with that general approach…

Ted

==== Ted Habermann ========================
Director of Earth Science, The HDF Group
Voice: (217) 531-4202
Email: thabermann@hdfgroup.org
==== HDF: Software That Powers Science ====

**Comment by cportele** [comment]
Just to explain: ShapeChange uses identifiers from EA to ensure that the identifiers are unique. Using names from the model would not do this. 

Of course, where one knows that using the names would result in unique identifiers, this could be a configuration option, but it would require a pull request to support such a capability.

**Comment by ejbleys** [comment]
Thanks
I am impressed that you have managed to turn the 19115 code list around
Happy with the form of the content for the https://github.com/ISO-TC211/XML/blob/master/standards.iso.org/19115/-3/cit/1.0/codelists.xml
Am I correct in thinking that cat:codeEntry/cat:CT_CodelistValue/cat:name has been omitted from https://raw.githubusercontent.com/ISO-TC211/XML/9641d72092984c421788bb6f1d5afcf50261beef/standards.iso.org/19115/resources/Codelists/cat/codelists.xml ?

I see 1 issues remaining with the code list as it stands: How to differentiate languages in cat:codeEntry/cat:CT_CodelistValue/cat:name?
     ?Use codeSpace?

There is a governance issue: What and when to promote material to http://standars.iso.org/...?
Cheers

e

**Pull request merged**
